services:
  backend:
    restart: always
    build:
      context: ./backend
      target: production
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jojuhu
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
