apiVersion: v1
kind: Secret
metadata:
  name: jojuhu-secret
  namespace: jojuhu
  labels:
    app.kubernetes.io/name: jojuhu
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-production-min-32-chars-long"
  POSTGRES_USER: "jojuhu"
  POSTGRES_PASSWORD: "jojuhu_secret"
  POSTGRES_DB: "jojuhu_backend"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"