stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build -t guigng/user-service:latest .
    - docker push guigng/user-service:latest

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
